### ISSUE TITLE
maybe an interesting idea

### ISSUE THREAD

**Issue by riz7z** [The-Ethical-Guy/Evan#1]
Idea) Is it possible to implement that the user does not use an API key, but uses local models (that are trained on code), as recently implemented in open-interpreter (https://github.com/KillianLucas /open-interpreter). Question) Another question, did you use the newest Jailbreaks or did you give the model a specific role (preliminary question to each question)? Thanks for your answer.

**Comment by The-Ethical-Guy** [comment]
first it's a very nice idea fr but the Evan depends on the api headers to bypass openai waf 
but in a thing like open-interpreter i will need to make a specific role for every single message and that's will take some time but you know i can find another way :)

second i used the api headers
